package net.caiban.auth.dashboard.domain.auth;

import java.util.Date;

/**
 * AuthUser generated by MyEclipse Persistence Tools
 */

public class AuthUser implements java.io.Serializable {

	// Fields

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String username;
	private String password;
	private String email;
	private Integer steping;
	private Date gmtCreated;
	private Date gmtModified;
	/**
	 * 
	 */
	public AuthUser() {
		super();
		// TODO Auto-generated constructor stub
	}
	/**
	 * @param username
	 * @param password
	 * @param email
	 * @param steping
	 * @param gmtCreated
	 * @param gmtModified
	 */
	public AuthUser(String username, String password, String email,
			Integer steping, Date gmtCreated, Date gmtModified) {
		super();
		this.username = username;
		this.password = password;
		this.email = email;
		this.steping = steping;
		this.gmtCreated = gmtCreated;
		this.gmtModified = gmtModified;
	}
	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	/**
	 * @return the username
	 */
	public String getUsername() {
		return username;
	}
	/**
	 * @param username the username to set
	 */
	public void setUsername(String username) {
		this.username = username;
	}
	/**
	 * @return the password
	 */
	public String getPassword() {
		return password;
	}
	/**
	 * @param password the password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}
	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}
	/**
	 * @return the steping
	 */
	public Integer getSteping() {
		return steping;
	}
	/**
	 * @param steping the steping to set
	 */
	public void setSteping(Integer steping) {
		this.steping = steping;
	}
	/**
	 * @return the gmtCreated
	 */
	public Date getGmtCreated() {
		return gmtCreated;
	}
	/**
	 * @param gmtCreated the gmtCreated to set
	 */
	public void setGmtCreated(Date gmtCreated) {
		this.gmtCreated = gmtCreated;
	}
	/**
	 * @return the gmtModified
	 */
	public Date getGmtModified() {
		return gmtModified;
	}
	/**
	 * @param gmtModified the gmtModified to set
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}
	
	

}